# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scott Kilts
email: hello@scottkilts.com
description: > # this means to ignore newlines until "baseurl:"
  Scott Kilts is a creative designer and developer located in Tacoma, WA. 
  Specializing in hand lettering, watercolor and research-based botique 
  websites hand-crafted to provide an exceptional user experience. 
baseurl: "/scottkilts" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sjkilts
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-coffeescript
  - bourbon
  - neat
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
include: ["_pages"]
permalink: /:title/
sass: 
  sass_dir: _sass
  style: compressed
repository: sjkilts/sjkilts.github.io
