# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scott Kilts - designer / illustrator
email: scott@scottkilts.com
description: > # this means to ignore newlines until "baseurl:"
  Scott Kilts is a creative designer and developer located in Tacoma, WA. 
  Specializing in hand lettering, watercolor and research-based botique 
  websites. 
#hand-crafted to provide an exceptional user experience. 
#baseurl: "www.scottkilts.com" # the subpath of your site, e.g. /blog
url: "http://www.scottkilts.com" # the base hostname & protocol for your site, e.g. http://example.com

github: [metadata]

github_username:  sjkilts
twitter_username: twitter_username

repository: sjkilts/sjkilts.github.io

# Build settings
markdown: kramdown
highlighter: rouge


# Pagination
paginate: 5
paginate_path: "/:num/"

#category_dir: "portfolio"
#category_layout: ""

collections:
  portfolio:
    output: true
    permalink: /:path/

# Ruby Gems
gems:
  - Jekyll-paginate
  - pygments
  - jekyll-coffeescript
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

include:

permalink: /:title/

sass: 
  style: compressed
